defaults:
  - _self_
  - optimizer@_global_: adam
  - scheduler@_global_: no_scheduler
trainer_name: temp

inner_update_steps: ${task_batch_size}
meta_loss: maml
inner_updates_lr: 1e-1
trainer_suffix: ''
meta_weight_decay: 0
preserve_inner_changes: false
meta_reset_class_weights: true
meta_reset_random_classes: 5
meta_inner_losses_coeff: 0
record_learned_classes: false
meta_aggregate_task_data: true
meta_only_use_task_data: false

meta_lr_scheduler:

trainer:
  _target_: meta_learning_models.MetaLearningClassifier
  device: ${device}
  learner: ${learner}
  inner_updates_lr: ${inner_updates_lr}
  inner_update_steps: ${inner_update_steps}

  meta_optim_name: ${meta_optim_name}
  meta_lr: ${meta_lr}
  meta_optim_kwargs: ${meta_optim_kwargs}
  meta_lr_scheduler: ${meta_lr_scheduler}
  meta_lr_scheduler_kwargs: ${meta_lr_scheduler_kwargs}

  meta_aggregate_task_data: ${meta_aggregate_task_data}
  meta_reset_class_weights: ${meta_reset_class_weights}
  meta_reset_random_classes: ${meta_reset_random_classes}
  meta_loss: ${meta_loss}
  meta_weight_decay: ${meta_weight_decay}
  meta_inner_losses_coeff: ${meta_inner_losses_coeff}
  preserve_inner_changes: ${preserve_inner_changes}
  record_learned_classes: ${record_learned_classes}
  meta_only_use_task_data: ${meta_only_use_task_data}